// Copied from svd2rust generated file (before fixing top level macros)
#![deny(dead_code)]
#![deny(improper_ctypes)]
#![deny(missing_docs)]
#![deny(no_mangle_generic_items)]
#![deny(non_shorthand_field_patterns)]
#![deny(overflowing_literals)]
#![deny(path_statements)]
#![deny(patterns_in_fns_without_body)]
#![deny(private_in_public)]
#![deny(unconditional_recursion)]
#![deny(unused_allocation)]
#![deny(unused_comparisons)]
#![deny(unused_parens)]
#![deny(while_true)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
// Include autogenerated docs
#![doc = include!(concat!(env!("OUT_DIR"), "/doc.txt"))]
// Import generated file
include!(concat!(env!("OUT_DIR"), "/generated.rs"));